### ISSUE TITLE
Add ability to automatically send all events in buffer at a regular time interval

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-python-tracker#114]
See https://github.com/snowplow/snowplow-dotnet-tracker/issues/3

**Comment by alexanderdean** [comment]
As in a regular flush

**Comment by alexanderdean** [comment]
What's the parameter going to be called?

**Comment by chuwy** [comment]
So far this is `set_flush_timer(time)` method as in .Net tracker.

**Comment by yalisassoon** [comment]
I can't get this to work locally:

```
from snowplow_tracker import AsyncEmitter
e1 = AsyncEmitter("collector-rt-demo.snplow.com", method="post")
e1.set_flush_timer(5)
t1 = Tracker(e1)
t1.track_struct_event("test", "single event flush")
```

I then wait a couple of minutes to see if the event turns up in ES (it should be flushed after 5 seconds) and it doesn't. In contrast if I send the data syncronously it turns up immediately.

Am I testing it correctly?

**Comment by yalisassoon** [comment]
Just to add - if I then execute

```
t1.flush()
```

The data comes through fine.

**Comment by chuwy** [comment]
This was fixed.
