### ISSUE TITLE
Ensure thread safety

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-python-tracker#130]
Make sure that multiple threads can't simultaneously send the same event.

**Comment by fblundun** [comment]
Possibly by using this module: https://docs.python.org/3/library/queue.html

**Comment by alexanderdean** [comment]
@fblundun is this the race condition you were just talking about?

**Comment by fblundun** [comment]
This ticket was just a reminder to check for the existence of race conditions. It turns out that there is one which manifests when the tracker has access to multiple cores - if enough events are sent asynchronously at once, an event will occasionally go missing.

**Comment by fblundun** [comment]
We expect that some people will use the on_failure callback to pass failed events back into the emitter. The callback gets called by a background thread created by the emitter. This means that as well as making the emitter internally thread-safe, we should make it safe for the user to access the emitter API concurrently from different threads.

**Comment by fblundun** [comment]
With the above queue-based implementation using Python 2.7, the program exiting can sometimes cause this exception:

```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/opt/python2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/opt/python2.7/lib/python2.7/threading.py", line 763, in run
  File "/vagrant/snowplow_tracker/emitters.py", line 312, in consume
  File "/opt/python2.7/lib/python2.7/Queue.py", line 168, in get
  File "/opt/python2.7/lib/python2.7/threading.py", line 332, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

This is a [known Python bug](http://bugs.python.org/issue14623). I don't think it actually causes any problems.

Interestingly it can be avoided by calling `time.sleep(1)` before exiting.
