### ISSUE TITLE
Add ability to set Subject per event

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-python-tracker#158]
At the moment the subject property is mutable state. Locks need to be used to ensure that different threads which change the subject are correctly interleaved.

**Comment by fblundun** [comment]
One approach: we could make the subject an argument to all the trackXXX methods.

**Comment by dcrasto** [comment]
I concur. With the suggestion. It makes idempotent.

**Comment by camerondavison** [comment]
This ticket is really old, but was the exact first thing that I was thinking about whenever the docs https://github.com/snowplow/snowplow/wiki/Python-Tracker#37-tracking-multiple-subjects said to call `t.set_subject(s1)` before calling another event. 

I am thinking that the Tracker needs to be `ThreadLocal` but then we can share an `AsyncEmitter` across multiple trackers? What is the through process around using a tracker in something like Flask that has multiple threads servicing requests.
