### ISSUE TITLE
Add `track_self_describing_event()` method

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-python-tracker#160]
Functionally equivalent to `track_unstruct_event()` but better named.

**Comment by yalisassoon** [comment]
As part of this we should update the documentation so that:

1. There is no more reference to 'unstructured events' (only `self-describing events`)
2. The old method is labelled as deprecated

I can have a go at updating the docs once I'm done with the testing

**Comment by chuwy** [comment]
What's deprecation plan for `track_unstruct_event`? I can add `DeprecationWarning` printning to stdout for first `track_unstruct_event` call.
