### ISSUE TITLE
Documentation: update example for track_site_search

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-python-tracker#176]
Currently the example is for a `track_page_view` rather than a `track_site_search`.

In general we should have an example for every method: this is as important as having a table with the arguments.

Ideally I'd like two examples for each track method:

1. One minimal (fewest number of fields)
2. One maximal (all fields set e.g. with the true timestamp and a couple of custom contexts thrown in)

**Comment by chuwy** [comment]
Fixed. Closing as QA.
