### ISSUE TITLE
Emitter: Don't initialize Celery app on module import

### ISSUE THREAD

**Issue by mattnibs** [snowplow/snowplow-python-tracker#185]
I'm adding your snowplow-python-tracker to my django app right now. Currently I'm running into an issue whenever I import the Emitter class. Looking at your code, you guys seem to do some stuff to create a Celery app in the main body of the Emitter module. The problem in my current case is that this code gets executed before my logic to create the default celery app for my django project. As a result, the default celery app get's set to Snowplow and celery stops working for my app. Seems to me this logic should be set in `__init__` of the `CeleryEmitter` instead. There's plenty of ways for me to work around this for now, but I thought you guys should be aware of this. It took me a while to identify this as the central cause, and may trip up others in similar situations. I'm happy to throw up a fix, if you guys would like that.

**Comment by alexanderdean** [comment]
Thanks for raising @mnibecker - a PR would be awesome!

**Comment by juliomenendez** [comment]
👍

**Comment by camerondavison** [comment]
post this issue landing would it be possible to move `celery` to be an option dependency? I have seen this done well in a lot of projects. Like https://github.com/stevearc/pypicloud/blob/f26415285bc9ba2271b19616e93c0e5673ea588f/setup.py#L32-L38 where you can pick if you want to include certain extras depending on if you are using them or not.
It is a bunch of code to bring in
```
├── celery >=4.0,<5.0
│   ├── billiard >=3.6.3.0,<4.0
│   ├── kombu >=4.6.10,<4.7
│   │   └── amqp >=2.6.0,<2.7
│   │       └── vine >=1.1.3,<5.0.0a1
```
if you are not going to use it.

**Comment by oguzhanunlu** [comment]
Hey @camerondavison , could you please create a new issue? This issue is handled at https://github.com/snowplow/snowplow-python-tracker/pull/196 and we missed to close this one back then. Thanks in advance!
