### ISSUE TITLE
Bump requests to latest version

### ISSUE THREAD

**Issue by rn-c1** [snowplow/snowplow-python-tracker#195]
The requests package in `setup.py` is really old, and it breaks compatibility with other packages that I would like to have installed in the same virtualenv.

This could be as easy as changing `"requests==2.2.1",` to `"requests>=2.2.1",` in `setup.py`.

**Comment by chuwy** [comment]
Good point. Let's make Python Tracker compatible to latest version in next release and pin it in `setup.py`.

Though if it is possible I would factor out as many dependencies from trackers as possible.
