### ISSUE TITLE
docstring on_failure description does not match function

### ISSUE THREAD

**Issue by mark-walle** [snowplow/snowplow-python-tracker#216]
I think that these docstrings:

https://github.com/snowplow/snowplow-python-tracker/blob/91da00a0549f05169b179c819028409d3d3f7401/snowplow_tracker/emitters.py#L88

https://github.com/snowplow/snowplow-python-tracker/blob/91da00a0549f05169b179c819028409d3d3f7401/snowplow_tracker/emitters.py#L347

should read something closer to:

`Callback executed if at least one HTTP request in a flush has status code other than 200`

Noting that this ignores the range suggested in `is_good_status_code(status_code)` since the docstring for `on_success` also ignored it.

**Comment by BenFradet** [comment]
good catch :+1: , feel free to open a pr

**Comment by mark-walle** [comment]
PR #217
