### ISSUE TITLE
Allow celery and redis to be optional dependencies

### ISSUE THREAD

**Issue by camerondavison** [snowplow/snowplow-python-tracker#232]
would it be possible to move `celery` to be an option dependency? I have seen this done well in a lot of projects. Like https://github.com/stevearc/pypicloud/blob/f26415285bc9ba2271b19616e93c0e5673ea588f/setup.py#L32-L38 where you can pick if you want to include certain extras.

It is a bunch of code to bring in
```
├── celery >=4.0,<5.0
│   ├── billiard >=3.6.3.0,<4.0
│   ├── kombu >=4.6.10,<4.7
│   │   └── amqp >=2.6.0,<2.7
│   │       └── vine >=1.1.3,<5.0.0a1
```
if you are not going to use it.

**Comment by AlexBenny** [comment]
Thanks @camerondavison for raising this up!
We will resolve this in the next Python tracker release which is currently scheduled for Q4 2020.

**Comment by andehen** [comment]
Any update on when a release where this is resolved will happen?

**Comment by paulboocock** [comment]
Hey @andehen 
We unfortunately had to drop the Python Tracker release scheduled in Q4 2020 due to other priorities. It's still on our roadmap to update this tracker and include this fix, but I think realistically it'll be in Q2 2021 before we look at this now.

Apologies for not updating this ticket sooner.

**Comment by andehen** [comment]
Thanks for the update @paulboocock!

I think we can get started by making a fork of this.

**Comment by paulboocock** [comment]
If you do manage to get a fork up and running, we're very open to a PR and that will speed up an official release with this fix too. Just throwing that idea out there 😉
