### ISSUE TITLE
Add Python 3.10 support

### ISSUE THREAD

**Issue by aleehedl** [snowplow/snowplow-python-tracker#254]
Currently, Python 3.10 is not supported. Is it on the roadmap?

For what I know, `contracts` library may be an issue because it hasn't been updated in years and now some warnings turn into errors.

**Comment by paulboocock** [comment]
Yep, it's definitely on the roadmap. I hope we will find time to look at this during Q4 2021.

We're open to PRs if you (or anyone reading this) would like to contribute to this tracker.
