### ISSUE TITLE
Add configurable timeout for HTTP requests

### ISSUE THREAD

**Issue by DDeyanov** [snowplow/snowplow-python-tracker#258]
Currently I'm not able to configure the timeout for GET and POST HTTP requests in the Emitter. This sometimes creates problems because in case of networking issues or unresponsive collector the requests are hanging indefinitely.

I'd like to be able to configure this timeout by passing it's value to the Emitter during initialization.

We've worked around this issue in some cases by wrapping the events emitting code with python signals and firing an alarm after some predefined timeout which suspends the code execution, but this approach works only if the code is running in the main thread.

If you like the proposal, I'm happy to send a PR.

**Comment by paulboocock** [comment]
Hey, thanks for the issue. We're more than happy to accept a PR for this and schedule a release for it (we have one planned to ensure everything is good in 3.10 so we can do it alongside that).
