### ISSUE TITLE
Stop defaulting to HTTP instead of HTTPS

### ISSUE THREAD

**Issue by medicinal-matt** [snowplow/snowplow-python-tracker#262]
**Describe the bug**
Unlike the other trackers, Python defaults to HTTP. This is confusing as you can use Python to quickly test the collector that also silently accepts HTTP, but will fail HTTPS unless you do more configuration. See [this thread](https://discourse.snowplowanalytics.com/t/why-does-snowplow-still-default-to-http-add-option-to-disable-it/6460) and [this thread](https://discourse.snowplowanalytics.com/t/solved-collector-does-not-accept-https-port-443-calls/6458)

[Here it is in the code](https://github.com/snowplow/snowplow-python-tracker/blob/release/0.10.0/snowplow_tracker/emitters.py#L54)

**Comment by AlexBenny** [comment]
Thanks @medicinal-matt for the heads up on this!
We are planning to standardise the features between the various trackers. The default configuration is certainly a point where we intend to work.
I'm closing this issue and I prioritise the original one.
