### ISSUE TITLE
poetry issue

### ISSUE THREAD

**Issue by MuslimBeibytuly** [snowplow/snowplow-python-tracker#319]
**Describe the bug**
```Note: This error originates from the build backend, and is likely not a problem with poetry but with minimal-snowplow-tracker (0.0.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "minimal-snowplow-tracker (==0.0.2)"'.```

**To Reproduce**
Steps to reproduce the behavior or code snippets that produce the issue.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Version [e.g. 3.8]

**Additional context**

**Comment by matus-tomlein** [comment]
Hi @MuslimBeibytuly, unfortunately `minimal-snowplow-tracker` is not our package or one that we maintain (it also seems abandoned). This repository only publishes the [`snowplow-tracker` package](https://pypi.org/project/snowplow-tracker/), which we recommend to be used for tracking Snowplow events from Python.
