### ISSUE TITLE
`track_self_describing_event()` is called with an unexpected keyword argument `true_timestamp`

### ISSUE THREAD

**Issue by andehen** [snowplow/snowplow-python-tracker#350]
**Describe the bug**
`track_self_describing_event()` is called with an unexpected keyword argument `true_timestamp`. The keyword it expects is named `tstamp`. Seems like a typo?

F.ex [here](https://github.com/snowplow/snowplow-python-tracker/blob/f722a96d43917e855a17557cf896e7dc47b8e587/snowplow_tracker/tracker.py#L383). Link to method definition [here](https://github.com/snowplow/snowplow-python-tracker/blob/f722a96d43917e855a17557cf896e7dc47b8e587/snowplow_tracker/tracker.py#L932).

**Comment by Jack-Keene** [comment]
Hi @andehen, 
Thanks for raising this issue, we've released a patch release 1.0.1 to fix this!

**Comment by andehen** [comment]
> Hi @andehen, Thanks for raising this issue, we've released a patch release 1.0.1 to fix this!

Thanks for the quick fix! 👍
