### ISSUE TITLE
Add a py.typed file so that mypy will know to use your inline type annotations

### ISSUE THREAD

**Issue by ted-marozzi** [snowplow/snowplow-python-tracker#360]
**Is your feature request related to a problem? Please describe.**
The problem is I have to reimplement your typings that you already maintain with your inline types, this is extra work for no reason.

**Describe the solution you'd like**
Add a py.typed file to the dist bundle so that mypy will use your inline types.

**Describe alternatives you've considered**
Reimplementing the typings on our end. This in unnecessary and cost time + effort.

**Additional context**
[Here is some additional info on py.typed](https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/)

**Comment by edgarrmondragon** [comment]
I opened a PR to address this: https://github.com/snowplow/snowplow-python-tracker/pull/362
