### ISSUE TITLE
Bug in Payload -> get()/ page_view.page_title

### ISSUE THREAD

**Issue by kenvac** [snowplow/snowplow-python-tracker#361]
**Describe the bug**
When attempting to access the page_title attribute of a PageView object, a TypeError is raised. This error occurs due to an incorrect usage of the get method on the payload dictionary within the page_title method.

**To Reproduce**
```python
>>> from snowplow_tracker import PageView
>>> page_view = PageView(page_url="https://www.snowplow.io",page_title="Homepage",event_subject="test")
>>> page_view.page_title
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/test/.pyenv/versions/3.8.10/envs/test/lib/python3.8/site-packages/snowplow_tracker/events/page_view.py", line 80, in page_title
    return self.payload.get("page")
TypeError: get() takes 1 positional argument but 2 were given
```

**Expected behavior**
The page_title attribute should return the title of the page without raising an error.

**Environment (please complete the following information):**
 - OS: Mac OS 14.5
 - Python version: 3.8.10
 - Version 1.0.2

**Additional context**
Possible fix or override `__get__()` to return self.nv_pairs
```python
    def get(self, key) -> PayloadDict:
        """
        Returns the value of dictionary from the Payload object
        """
        return self.nv_pairs.get(key)
```

**Comment by greg-el** [comment]
Thanks for reporting this @kenvac! This is now being worked on and will be addressed in the next release of the tracker.
