### ISSUE TITLE
Add Kinesis-backing for tracker

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-python-tracker#46]
If you are running the Snowplow Kinesis flow and using the Python Tracker on **your servers** (vs on your users' machines), you may not want the hop via the Snowplow Scala Collector - i.e instead of:

```
Python Tracker -> Scala Stream Collector -> Kinesis
```

you want to do:

```
Python Tracker -> Kinesis
```

This would use the Boto library for writing events to Kinesis. We would also need to use the Thrift Raw Event...

**Comment by matus-tomlein** [comment]
Closing due to lack of priority
